/******************************************************************************/
/***          Generated by IBExpert 2008.11.27 29/05/2016 13:57:41          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'fbclient.dll';

CREATE DATABASE 'D:\Areco\BANCO\ARECO.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_PRODUTOS_ID;
SET GENERATOR GEN_PRODUTOS_ID TO 8;



SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE SP_GEN_PRODUTOS_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^



SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CFOP (
    CODIGO           SMALLINT NOT NULL,
    DESCRICAO        VARCHAR(255),
    CODIGODESCRICAO  COMPUTED BY (cast(Codigo as varchar(10)) || '-' || Descricao)
);


CREATE TABLE PRODUTOS (
    ID                  INTEGER NOT NULL,
    DESCRICAO           VARCHAR(120),
    COD_BARRA           VARCHAR(13),
    PRECO_CUSTO         DECIMAL(7,2),
    ESTOQUE_MINIMO      INTEGER,
    POSICAO_ESTOQUE     INTEGER,
    PRECO_VENDA         DECIMAL(7,2),
    DATA_INCLUSAO       TIMESTAMP,
    OBSERVACOES         VARCHAR(300),
    NCM                 CHAR(8),
    CFOP                SMALLINT,
    SITUACAOTRIBUTARIA  VARCHAR(3)
);


CREATE TABLE SITUACAOTRIBUTARIA (
    CODIGO           VARCHAR(3) NOT NULL,
    TIPO             VARCHAR(5) NOT NULL,
    DESCRICAO        VARCHAR(255),
    CODIGODESCRICAO  COMPUTED BY (Codigo || '-' || Descricao)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CFOP ADD CONSTRAINT PK_CFOP PRIMARY KEY (CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID);
ALTER TABLE SITUACAOTRIBUTARIA ADD CONSTRAINT PK_SITUACAOTRIBUTARIA PRIMARY KEY (CODIGO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_CFOP FOREIGN KEY (CFOP) REFERENCES CFOP (CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_ST FOREIGN KEY (SITUACAOTRIBUTARIA) REFERENCES SITUACAOTRIBUTARIA (CODIGO);


/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE SP_GEN_PRODUTOS_ID
RETURNS (
    ID INTEGER)
AS
BEGIN
  ID = GEN_ID(GEN_PRODUTOS_ID, 1);
  SUSPEND;
END^



SET TERM ; ^
