/******************************************************************************/
/***          Generated by IBExpert 2008.11.27 29/05/2016 13:59:00          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'fbclient.dll';

CREATE DATABASE 'D:\Areco\BANCO\ARECO.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;

INSERT INTO CFOP (CODIGO, DESCRICAO) VALUES (5101, 'Venda de produção do estabelecimento');
INSERT INTO CFOP (CODIGO, DESCRICAO) VALUES (5102, 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CODIGO, DESCRICAO) VALUES (5103, 'Venda de produção do estabelecimento, efetuada fora do estabelecimento');
INSERT INTO CFOP (CODIGO, DESCRICAO) VALUES (5405, 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído');

COMMIT WORK;

INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('00', 'CST', 'Tributada integralmente');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('20', 'CST', 'Com redução de base de cálculo');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('40', 'CST', 'Isenta');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('41', 'CST', 'Não tributada');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('60', 'CST', 'ICMS cobrado anteriormente por substituição tributária');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('90', 'CST', 'Outras');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('102', 'CSOSN', 'Tributada pelo Simples Nacional sem permissão de crédito');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('300', 'CSOSN', 'Imune');
INSERT INTO SITUACAOTRIBUTARIA (CODIGO, TIPO, DESCRICAO) VALUES ('500', 'CSOSN', 'ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação');

COMMIT WORK;

INSERT INTO PRODUTOS (ID, DESCRICAO, COD_BARRA, PRECO_CUSTO, ESTOQUE_MINIMO, POSICAO_ESTOQUE, PRECO_VENDA, DATA_INCLUSAO, OBSERVACOES, NCM, CFOP, SITUACAOTRIBUTARIA) VALUES (7, 'BOLACHA NEGRESCO', '92839892382', 1, 30, 50, 1.34, '2016-05-29 12:39:12', NULL, '1223333 ', 5102, '500');

COMMIT WORK;

